#Imprimir el resultat de la suma de les dues variables (int)
x, y = (33,27)
z = (x+y)
print(z)
print(type(z))
#Imprimir el resultat de la suma de les dues variables (int) dintre d'un text (string)
x, y = (33,27)
z = (x+y)
print('El resultat de la suma es ' + str(z))